// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package commit

import mock "github.com/stretchr/testify/mock"

// MockQueryProvider is an autogenerated mock type for the QueryProvider type
type MockQueryProvider struct {
	mock.Mock
}

// TransactionStatus provides a mock function with given fields: channelName, transactionID
func (_m *MockQueryProvider) TransactionStatus(channelName string, transactionID string) (*Status, error) {
	ret := _m.Called(channelName, transactionID)

	var r0 *Status
	if rf, ok := ret.Get(0).(func(string, string) *Status); ok {
		r0 = rf(channelName, transactionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Status)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(channelName, transactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
